### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by Aliveallah** [OpenFreeRealms/OpenFreeRealms#7]
When I try to launch the game it says windows cannot find "freerealms.exe". I tried a lot of videos  nothing worked so now I'm messaging you to see if you have any idea of what going on. Thanks in advance!

**Comment by StimpyDev** [comment]
I think its better to ask that question in the discord server.

https://discord.gg/j7Yeu3BV

**Comment by Aliveallah** [comment]
> I think its better to ask that question in the discord server.
> 
> https://discord.gg/j7Yeu3BV

Okay thanks
